### ISSUE TITLE
Добавить систему справки

### ISSUE THREAD

**Issue by Funny-Mole** [P4106/avi2hex#2]

**Comment by Funny-Mole** [comment]
Справка должна отражать основные функции программы и их описание, а также пример использования

**Comment by AVVeronika** [comment]
Предлагаю при вводе команды --help или ошибке синтаксиса выводить следующее:
print("Usage:")
    print("Convert image to hex-file: avi2hex --operation img2hex --input image_file --output hex_file [--resize width height]")
    print("Convert hex-file to image: avi2hex --operation hex2img --input hex_file --output image_file")
    print("Convert video to hex-file: avi2hex --operation avi2hex --input video_file --output hex_file [--reduce frame] [--resize width height]")
    print("Convert hex-file to video: avi2hex --operation hex2avi --input hex_file --output video_file --fps fps")

Но полное описание команд нужно отразить в README
