### ISSUE TITLE
Реализовать метод преобразования hex-последовательности в видеофайл

### ISSUE THREAD

**Issue by AVVeronika** [P4106/avi2hex#8]

**Comment by AVVeronika** [comment]
Входные данные: hex-файл, число кадров в секунду
Выходные данные: видеофайл формата avi

**Comment by kimavr** [comment]
А каким образом определяются границы кадра?

**Comment by AVVeronika** [comment]
Ширина кадра: количество hex-чисел в строке
По высоте кадры разделены символами \r\n
